---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install basic packages
      apt:
        name:
          - curl
          - wget
          - vim
        state: present

    - name: Check system information
      shell: |
        echo "Hostname: $(hostname)"
        echo "OS: $(cat /etc/os-release | grep PRETTY_NAME)"
        echo "Architecture: $(uname -m)"
      register: system_info

    - name: Display system info
      debug:
        var: system_info.stdout_lines
